Fix for python3 TypeError for 'dict_keys'
TypeError: 'dict_keys' object does not support indexing

Explanation:
In python2x, edid_map.keys() returned a list.
With python3.x, it returns a dict_keys object, which behaves more like a set instead of list.

Inspired from:
http://stackoverflow.com/questions/17322668/xi-xj-xj-xi-typeerror-dict-keys-object-does-not-support-indexing

I tested this change with python2, and it seems to work.